### ISSUE TITLE
`yarn build` throws "Error occured:  _h.match is not a function" on fresh clone

### ISSUE THREAD

**Issue by almndbtr** [ourzora/v3#142]
## Summary

Starting with a fresh clone of https://github.com/ourzora/v3/commit/479e45ccf29b2c9fe48cdf60373212c45c060e56, changing directory into the repo, running `yarn` to install dependencies, and running `yarn build` throws this error:

> "Error occured:  _h.match is not a function"

<details>

<summary>Full trace</summary>

```console
$ git rev-parse HEAD
479e45ccf29b2c9fe48cdf60373212c45c060e56

$ yarn
yarn install v1.22.15
[1/4] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 0.26s.

$ yarn build --show-stack-traces
yarn run v1.22.15
$ forge build && yarn typechain --show-stack-traces
compiling...
no files changed, compilation skipped.
$ typechain --target=ethers-v5 'dist/artifacts/*/*.json' --out-dir dist/typechain --show-stack-traces
Error occured:  _h.match is not a function
Stack trace:  TypeError: _h.match is not a function
    at extractBytecode (/workspaces/v3/node_modules/typechain/dist/parser/abiParser.js:217:70)
    at Ethers.transformAbiOrFullJsonFile (/workspaces/v3/node_modules/@typechain/ethers-v5/dist/index.js:55:58)
    at Ethers.transformFile (/workspaces/v3/node_modules/@typechain/ethers-v5/dist/index.js:30:21)
    at runTypeChain (/workspaces/v3/node_modules/typechain/dist/typechain/runTypeChain.js:54:82)
    at async main (/workspaces/v3/node_modules/typechain/dist/cli/cli.js:49:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

### Investigating the trace 🔎

I `grep`'d for this function call:

```
$ grep -rn "_h.match" .
./node_modules/typechain/dist/parser/abiParser.js:217:    if ((_h = json.bytecode) === null || _h === void 0 ? void 0 : _h.match(bytecodeRegex)) {
```

Here's the full expression in context:

```js
    if ((_h = json.bytecode) === null || _h === void 0 ? void 0 : _h.match(bytecodeRegex)) {
        return extractLinkReferences(json.bytecode, json.linkReferences);
    }
```

I pulled up [`packages/typechain/src/parser/abiParser.ts` at `main`](https://github.com/dethcrypto/TypeChain/blob/master/packages/typechain/src/parser/abiParser.ts) and I think [this is the source](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L399-L401):

```ts
  if (json.bytecode?.match(bytecodeRegex)) {
    return extractLinkReferences(json.bytecode, json.linkReferences)
  }
```

I stopped here - could there be a mismatch in either platform or software requirements? 💭

For reference, I've made sure that [Foundry](https://github.com/gakonst/foundry) is installed for these different environments and I still get the same error:

- `Ubuntu 20.04.3 LTS`
- `Mac OS Monterey v12.2.1`

Would love a pointer for how to get `yarn build` working on my machine! 🙇‍♂️

**Comment by almndbtr** [comment]
### Update: using Actions to reproduce this error

I noticed this project has a [GitHub Actions workflow file](https://github.com/almndbtr/v3/blob/main/.github/workflows/test.yml). I [created a new branch](https://github.com/almndbtr/v3/compare/main...ourzora-v3-142) updating the workflow to include [`yarn build`](https://github.com/almndbtr/v3/blob/04977e17376f4fc0196945499b9ac136f0fb000f/.github/workflows/test.yml#L22-L23) as a part of the run. 

This [failing workflow run](https://github.com/almndbtr/v3/actions/runs/1906224838) demonstrates the [failure when the contracts are compiled](https://github.com/almndbtr/v3/runs/5350514174?check_suite_focus=true#step:6:14) after the respective dependencies are installed.

**Comment by almndbtr** [comment]
### Update: digging into `yarn typechain`

To see if this had ever been reported prior, I searched [Dethcrypto/TypeChain](https://github.com/dethcrypto/TypeChain/issues?q=is%3Aissue+is%3Aopen+_h.match+is+not+a+function) for relevant issues -- none surface that would be relevant.

From what I've gathered so far, I think the issue may likely be related to the `typechain` utility than with this project itself. I'd love the team's feedback on this, since this currently blocks (at least, for me) local development of recompiling the smart contracts on change and re-testing them for confidence. 🙇  cc: @kulkarohan @tbtstl 

#### Research 🕵️  

`yarn build` runs two commands:

https://github.com/ourzora/v3/blob/479e45ccf29b2c9fe48cdf60373212c45c060e56/package.json#L35

From the stack trace, the issue doesn't seem to be with `forge build` but instead with `yarn typechain`:

https://github.com/ourzora/v3/blob/479e45ccf29b2c9fe48cdf60373212c45c060e56/package.json#L40

Consulting Typechain's [Usage - CLI section](https://github.com/dethcrypto/TypeChain#cli), this is my layperson's interpretation of the command:

> _Hey typechain! Try loading `@typechain/ethers-v5` as your target. Your `glob` (pattern to find the ABIs) is `dist/artifacts/*/*.json`. With whatever you find, put all the generated files in `dist/typechain`._

Kicking off a [new workflow run with that flag enabled](https://github.com/almndbtr/v3/runs/5358844382?check_suite_focus=true#step:7:1) gives us a bit more context:

```console
$ typechain --target=ethers-v5 'dist/artifacts/*/*.json' --out-dir dist/typechain --show-stack-traces
Error occured:  _h.match is not a function
Stack trace:  TypeError: _h.match is not a function
    at extractBytecode (/home/runner/work/v3/v3/node_modules/typechain/dist/parser/abiParser.js:21[7](https://github.com/almndbtr/v3/runs/5358844382?check_suite_focus=true#step:7:7):70)
    at Ethers.transformAbiOrFullJsonFile (/home/runner/work/v3/v3/node_modules/@typechain/ethers-v5/dist/index.js:55:5[8](https://github.com/almndbtr/v3/runs/5358844382?check_suite_focus=true#step:7:8))
    at Ethers.transformFile (/home/runner/work/v3/v3/node_modules/@typechain/ethers-v5/dist/index.js:30:21)
    at runTypeChain (/home/runner/work/v3/v3/node_modules/typechain/dist/typechain/runTypeChain.js:54:82)
    at async main (/home/runner/work/v3/v3/node_modules/typechain/dist/cli/cli.js:4[9](https://github.com/almndbtr/v3/runs/5358844382?check_suite_focus=true#step:7:9):20)
error Command failed with exit code 1.
```

`src/parser/abiParser.ts` exports [`extractBytecode`](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L363). Here's my read of that block:

- If what's passed in is a `.bin` file with just the bytecode, extract those link references. [#](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L374-L375)
- Otherwise, it's likely a JSON file. Try parsing it before processing. [#](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L377-L382)
  - Short-circuit execution if parsing the JSON threw an error. [#](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L384)
- Try processing the JSON file in this order based on the specified bytecode regex, returning the output of the extracted link references. - If none work, return `undefined` to indicate that nothing was extracted from this bytecode. [#](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L403)
  - `json.evm.bytecode` [#](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L387)
  - JSON schema of `@0x/sol-compiler` [#](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L392)
  - `json.bytecode` [#](https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/typechain/src/parser/abiParser.ts#L399)

Coming back to [the OP](https://github.com/ourzora/v3/issues/142#issue-1153236508), I think sending `.match` to `json.bytecode?` is what's causing the error. `json` is the deserialized string as a JavaScript object and `bytecode` is the expected key defined on that object. The inclusion of `?` at the end of `bytecode` would suggest that `bytecode` is a way of signifying [optional property access](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining).

**Comment by jerryge** [comment]
I have the same problem

**Comment by kulkarohan** [comment]
typechain support should be fixed after this! https://github.com/dethcrypto/TypeChain/pull/624

**Comment by iainnash** [comment]
I've found the issue the fix the typechain side here:
https://github.com/dethcrypto/TypeChain/pull/624

A temporary fix is to use the patched version of TypeChain or roll back forge/foundry to a version in mid-feburary before these changes landed: 
https://github.com/gakonst/foundry/issues/705

**Comment by almndbtr** [comment]
@iainnash @kulkarohan - Thank you for being so responsive! I will give those suggested workarounds a try and report back. 👍🏾

I hope it's cool that we leave this issue open until the more permanent fix is implemented, so other contributors who stumble upon this are aware and can take the appropriate measures for when they develop their changes for this project. 🙏🏾

**Comment by iainnash** [comment]
Looks like the typechain fix has been released.

https://github.com/dethcrypto/TypeChain/releases/tag/typechain%407.0.1

**Comment by kulkarohan** [comment]
rip lol now its failing with `Error occured:  _k.match is not a function` https://github.com/dethcrypto/TypeChain/issues/638

**Comment by almndbtr** [comment]
> `Error occured: _k.match is not a function`

I'm getting the same after about an hour of tinkering with the internals of typechain. 😕 

I see that https://github.com/dethcrypto/TypeChain/issues/638 is closed, but that doesn't resolve what's currently here. 

Will come back later when I'm fresh to see what else I could try to figure out what's going on.  💭

**Comment by kulkarohan** [comment]
typechain has fixed this! i've updated the dependencies accordingly here: https://github.com/ourzora/v3/commit/e1ab16ffb462979c34017ce32e940852cc3e7cc4

closing

**Comment by almndbtr** [comment]
Thank you for updating this, @kulkarohan ! 🙏
